### ISSUE TITLE
Areas of the documentation are out of date with the new UI and sometimes just plain wrong

### ISSUE THREAD

**Issue by RusseII** [multisig-labs/docs.gogopool.com#13]
https://docs.gogopool.com/readme-1/as-a-node-operator/as-a-node-operator this page in particular has a lot of stuff that's incorrect / misleading. 

For example it mentions 'borrowing' which isn't a thing as far as I'm aware 
![image](https://github.com/multisig-labs/docs.gogopool.com/assets/15036618/db65a289-f67d-4c7a-b3c0-7a8bd4063444)

Might be worth lightly looking through the metrics on our docs page and if there's significant traffic optimizing those specific flows. But if the traffic is bad it's prob not worth doing anything.

**Comment by Bookcliff** [comment]
Faucet link on [/as-a-node-operator/manual-setup](https://docs.gogopool.com/readme-1/as-a-node-operator/as-a-node-operator) broken
Looks like should be https://faucet.gogopool.com/ instead
<img width="1136" alt="CleanShot 2024-04-11 at 08 20 05@2x" src="https://github.com/multisig-labs/docs.gogopool.com/assets/99197390/e61673bc-3171-42e1-8e83-6df56f1b327e">

**Comment by Bookcliff** [comment]
https://docs.gogopool.com/design/how-liquid-staking-works#what-happens-to-the-users-staked-avax

Is the '(code reference)' supposed to be a link to the contract or something?

<img width="807" alt="CleanShot 2024-04-11 at 08 40 47@2x" src="https://github.com/multisig-labs/docs.gogopool.com/assets/99197390/8f3b1d97-e2ac-4593-a5b2-a4646d7ead6a">

**Comment by Namaskar-1F64F** [comment]
fixed both grace comments in https://app.gitbook.com/o/p7MjuTbiGIGCYSYtlVhV/s/JnYoMAcIL3VICHojy1yR/~/changes/87/
